### ISSUE TITLE
Conflict with PlanBuild mod

### ISSUE THREAD

**Issue by paul-cpp** [MSchmoecker/HammerTime#11] opened 2022-12-19 00:52 UTC
Hi! There is a conflict with PlanBuild mod. 
https://valheim.thunderstore.io/package/MathiasDecrock/PlanBuild/
When opening the construction menu, the name and cost of objects are not displayed and an error is thrown in logs:
`
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Player.GetAvailableBuildPiecesInCategory (Piece+PieceCategory cat) (at <035307060cbb4b30b916cd82ebd80490>:0)
`

**Comment by MSchmoecker** [comment] 2022-12-20 10:17
Thanks for the report. This isn't something I can reproduce with my setup, please send your full log file from BepInEx/LogOutput.log as well as your HammerTime config. 

By default the PlanBuild is not enabled in HammerTime, since it will not work when moving the pieces to the vanilla hammer because it uses the hammer for special functions. But this doesn't seem to be your issue anyway.

**Comment by MSchmoecker** [comment] 2023-02-16 13:54
As I cannot reproduce this, I will close it for now. If you have new information, feel free to open this issue again or create a new one.

**Closed by MSchmoecker** 2023-02-16 13:54 UTC
